{
    "uuid": "dfc138a5-f3e4-426e-9195-1cf85ad74ebd",
    "historyId": "ОбщийМодуль.СА_ПроцедурыСканАрхиваКлиент.Модуль. 408,3: Процедура или функция с указанным именем не определена",
    "name": "ОбщийМодуль.СА_ПроцедурыСканАрхиваКлиент.Модуль. 408,3: Процедура или функция с указанным именем не определена",
    "fullName": "ОбщийМодуль.СА_ПроцедурыСканАрхиваКлиент.Модуль. 408,3: Процедура или функция с указанным именем не определена",
    "start": 1661424439615,
    "stop": 1661424461326,
    "statusDetails": {
        "known": false,
        "muted": false,
        "flaky": false
    },
    "status": "failed",
    "stage": "finished",
    "steps": [],
    "parameters": [],
    "labels": [
        {
            "name": "package",
            "value": "ОбщийМодуль.СА_ПроцедурыСканАрхиваКлиент.Модуль"
        },
        {
            "name": "story",
            "value": "Процедура или функция с указанным именем не определена"
        },
        {
            "name": "feature",
            "value": "Синтаксическая проверка конфигурации. Конфигуратор"
        },
        {
            "name": "host",
            "value": "Синтаксическая проверка конфигурации. Конфигуратор"
        }
    ],
    "links": [],
    "attachments": [],
    "description": "Строка 408,3: Процедура или функция с указанным именем не определена (Предупреждение) #> <<?>>Предупреждение(\"Транзакция прервана!\"); (Проверка: Внешнее соединение)"
}
